### PR TITLE
Added optional userName and passWord to SimpleGdb

### PR DESCRIPTION
**Pull request by Christian-B**
Added the ability to handle userName and password to the connection without making then required.
This was desirable for security on our mySQL server.

The public methods exist in both the previous version and the new with userName and password version.
Non public method only have the new signature.

All getConnection methods check if userName is null. 
If so the methond without UserName is used.
If and only if userName and passWord are provided will they be used.

### CODE REVIEW

**Comment by amarillion** [comment]
I thought it would be possible to just make the username and password part of the connection string? I'm pretty sure I've done this in the past.

**Comment by amarillion** [comment]
Yeah, for example I've used this connection string in the past:

"idmapper-jdbc:mysql://localhost/snp?user=bridgedb"

**Comment by amarillion** [comment]
I'm inclined not to merge this, because adding these method signatures would encourage coding against implementation instead of using generic interfaces.

**Comment by Christian-B** [comment]
Yes the connectionString "jdbc:mysql://localhost:3306/" + dbName + "?user=theUser&password=thePassWord" works like a cham.
Absolutely no need for this.

**Pull request closed without merging**
